name: keepInv
version: '1.2.1'
main: org.koishio.keepInv.KeepInv
author: "koishio"
api-version: '1.21'
permissions:
  keepinv.get:
    description: 允许查看自己的死亡掉落状态
    default: op
  keepinv.set:
    description: 允许设置自己的死亡掉落状态
    default: op
  keepinv.toggle:
    description: 允许切换自己的死亡掉落状态
    default: op
  keepinv.reset:
    description: 允许重置自己的死亡掉落状态
    default: op
  keepinv.get.others:
    description: 允许查看他人的死亡掉落状态
    default: op
  keepinv.set.others:
    description: 允许设置他人的死亡掉落状态
    default: op
  keepinv.toggle.others:
    description: 允许切换他人的死亡掉落状态
    default: op
  keepinv.reset.others:
    description: 允许重置他人的死亡掉落状态
    default: op